[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://54.81.190.224/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api"
  to = "http://54.81.190.224/api"
  status = 200
  force = true
